using UnityEngine;
using TMPro;
 
public class TextoDa침oTablero : MonoBehaviour
{
    [SerializeField] TextMeshProUGUI m_Object;
    [SerializeField] GameObject textoCompleto;
    [SerializeField] bool isPlayer;
    string texto;
    void Start()
    {
          texto = m_Object.GetComponent<TMPro.TextMeshProUGUI>().text;
          texto = "Inici칩 sin problemas";

    }

    private void Update() 
    {
        if (isPlayer)
        {
            texto = SistemaDeTurnos.Instance.Get_Da침oCarta().ToString();
            textoCompleto.SetActive(!SistemaDeTurnos.Instance.Get_TurnoPlayer());
        }
        else
        {
            texto = SistemaDeTurnos.Instance.Get_Da침oCarta().ToString();
            textoCompleto.SetActive(SistemaDeTurnos.Instance.Get_TurnoPlayer());
        }
    }
}